version: '2'
services:
  engine:
    image: ocr-java:latest
    container_name: docker-ocr-spike
    ports:
      - 8080:8080
    depends_on:
      - redis

  redis:
    image: "redis:alpine"
    container_name: docker-redis
    ports:
      - 6379:6379
